version: '3.8'

services:
  react-app-template:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-22}
        - YARN_VERSION=${YARN_VERSION:-1.22.22}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "8080:8080"
    volumes:
      - .:/react-app-template
      - /react-app-template/node_modules
