version: '3.8'

services:
  react-app-template:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/react-app-template
      - /react-app-template/node_modules
